# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           ./docs
destination:      ./_site
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

exclude:
  - "jade"
  - "vendor"

# Custom vars
current_version:  3.1.0
repo:             https://github.com/twbs/bootstrap
sass_repo:        https://github.com/twbs/bootstrap-sass

download:
  source:         https://github.com/twbs/bootstrap/archive/v3.1.0.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.1.0/bootstrap-3.1.0-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.1.0.tar.gz

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js

info:
  site_name:    Bt-docs

meta:
  description:  dess
  keywords:     keywords
  author:       huqiu

navigation:
  name:    Bt-docs
  left:
    - path:     getting-started
      title:    Getting Started

analytics:
  google:
    account:    UA-43024238-1

