# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_site
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

exclude:
  - "conf"

info:
  site_name:    Cube SDK

meta:
  description:  A android development framework. It make loading image and network request easy.
  keywords:     Cube-SDK, Android development framework, Image Loader, Easy netwrok request.
  author:       liaohuqiu@gmail.com

navigation:
  name:    Cube
  left:
    - path:     /imageloader
      title:    Image Loader
    - path:     /request
      title:    Network Request
  right:
    - title:    Fork on Github
      path:     https://github.com/liaohuqiu/cube-sdk

analytics:
  google:
    account:    UA-43024238-1

download:
  rep:          https://github.com/liaohuqiu/cube-sdk
  dist:         https://github.com/liaohuqiu/cube-sdk/archive/master.zip
  apk:          https://github.com/liaohuqiu/cube-sdk/raw/master/cube-sdk-sample.apk
  qrcode:       /assets/img/qrcode.png
  google_play:   /


languages:      ["en", "cn"]
